INSERT INTO `areas` (`tipo_espacio`, `sede`, `area`) VALUES
('Aula', 'Belenes', '1'),
('Aula', 'Belenes', '2'),
('Aula', 'Belenes', '3'),
('Aula', 'Belenes', '4'),
('Aula', 'Belenes', '5'),
('Aula', 'Belenes', '6'),
('Aula', 'Belenes', 'HIBRIDO'),
('Aula', 'Belenes', 'ASINCRONIC'),
('Aula', 'Belenes', 'DESU'),
('Aula', 'Belenes', 'VIRTUAL'),
('Aula', 'Belenes', 'S J MGDS'),
('Aula', 'Belenes', 'nan'),
('Aula', 'Belenes', 'SALA JUNTA'),
('Aula', 'Belenes', 'FBD- CAG1'),
('Aula', 'Belenes', 'SALADEJUNT'),
('Aula', 'Belenes', 'PRACTICA'),
('Aula', 'Belenes', 'EN LINEA'),
('Aula', 'Belenes', 'AUDITORIO'),
('Aula', 'Belenes', 'DESMOS'),
('Aula', 'Belenes', 'MOODLE'),
('Aula', 'Belenes', 'FBD- CAG2'),
('Aula', 'Belenes', 'LINEA'),
('Aula', 'Belenes', 'FBC4'),
('Aula', 'Belenes', 'CUBICULO'),
('Aula', 'Belenes', 'FBA9'),
('Aula', 'Belenes', 'SALA DE JU');